name: Simple Workflow

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command
        run: echo "Hello, world!"
